[package]
name = "thunder"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[lib]
proc-macro = true

[dependencies]
clap = "*"
syn = { version = "*", features = ["extra-traits", "full", "fold", "visit", "visit-mut"] }
quote = "*"